server:
  port: 8083
management:
  server:
    port: 8080
logging:
  level:
    com.freelance.atelier_workshops: debug

spring:
  application:
    name: '@project.artifactId@'
    version: '@project.version@'
  datasource:
    url: jdbc:postgresql://${BBDD_HOST}:${BBDD_PORT}/${BBDD_NAME}
    username: ${BBDD_USER}
    password: ${BBDD_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        default_schema: atelier
        format_sql: true
    open-in-view: false
  web:
    resources:
      static-locations: ${STATIC_CLASSPATH_LOCATION:classpath:/static/},${STATIC_FILE_LOCATION}
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
application:
  security:
    auth:
      username: ${AUTH_USERNAME}
      password: ${AUTH_PASSWORD}
    jwt:
      secretKey: ${SECRET_KEY}
  image:
    upload:
      directory: ${UPLOAD_DIRECTORY:src/main/resources/static/images/}
      base-url: ${IMAGE_BASE_URL:http://localhost:8080/images/}
      local-directory: ${STATIC_FILE_LOCATION}

# ENVIRONMENT VARIABLES
BBDD_HOST: localhost
BBDD_PORT: 5434
BBDD_NAME: atelier
BBDD_USER: admin
BBDD_PASSWORD: password
STATIC_CLASSPATH_LOCATION: classpath:/static/
